/**
 * Codasip Ltd
 *
 * CONFIDENTIAL
 *
 * Copyright 2018 Codasip Ltd
 *
 * All Rights Reserved.
 *
 * NOTICE: All information contained in this file, is and shall remain the property of Codasip Ltd
 * and its suppliers, if any.
 *
 * The intellectual and technical concepts contained herein are confidential and proprietary to
 * Codasip Ltd and are protected by trade secret and copyright law.  In addition, elements of the
 * technical concepts may be patent pending.
 *
 * This file is part of the Codasip Studio product. No part of the Studio product, including this
 * file, may be use, copied, modified, or distributed except in accordance with the terms contained
 * in Codasip license agreement under which you obtained this file.
 *
 *  \file
 *  \author jan
 *  \date   22 Mar 2018
 *  \brief  Declaration/Implementation of the class.
 */

#ifndef INCLUDE_CODASIP_MISC_CUSTOMMVTCASES_INC_
#define INCLUDE_CODASIP_MISC_CUSTOMMVTCASES_INC_

#ifndef CASE
#error "CASE not defined"
#endif

CASE(i256)
CASE(i512)
CASE(i1024)
CASE(i2048)
CASE(v2i128)
CASE(v256i1)
CASE(v4i128)
CASE(v8i128)
CASE(v16i128)
CASE(v2048i1)

#endif  // INCLUDE_CODASIP_MISC_CUSTOMMVTCASES_INC_
